### ISSUE TITLE
search field 

### ISSUE THREAD

**Issue by RGHANILOO** [MohammedMalleck/weather-app#1]
as a user when i want to start searching for my city i would want the field to clear automatically when i click in the search field.
also the time out on the search maybe a tad too long 

Otherwise a super nice looking app

https://github.com/MohammedMalleck/weather-app/assets/26300368/4f2de785-0918-48c8-8f98-e6e3c18bb74f

**Comment by MohammedMalleck** [comment]
Ty for pointing out the feature!...I have updated both of your recommendations.
Check it out and let me know if i can improve this any further  

https://github.com/MohammedMalleck/weather-app/assets/167643639/fd9ab07d-3786-4de9-ad90-c3d1803d8d7c
